### ISSUE TITLE
Unable to verify signature produced with the ebay nodejs SDK

### ISSUE THREAD

**Issue by alexdawn** [eBay/digital-signature-verification-ebay-api#11] opened 2022-11-16 16:26 UTC
Running this docker on 8080 and the https://github.com/ebay/digital-signature-java-sdk on port 8081,

I used the /sign endpoint get the headers:
```bash
curl --location --request POST 'http://localhost:8081/sign' \
--header 'Content-Type: application/json' \
--data-raw '{"hello": "world"}'
```
using these headers the .validate endpoint is able to approve the signature, howvever the docker is not:
```bash
# check the nodejs sdk validates
curl --location -i --request POST 'http://localhost:8081/validate' \
--header 'Content-Type: application/json' \
--header 'Content-Digest: sha-256=:X48E9qOokqqrvdts8nOJRJN3OWDUoyWxBf7kbu9DBPE=:' \
--header 'Signature-Input: sig1=("content-digest" "x-ebay-signature-key" "@method" "@path" "@authority");created=1668613695' \
--header 'x-ebay-signature-key: eyJhbGciOiJBMjU2R0NNS1ciLCJlbmMiOiJBMjU2R0NNIiwiemlwIjoiREVGIiwiaXYiOiJwalh1LWlhY1NmRHNwc2lDIiwidGFnIjoiT090V2toaVV2NV9NZ2YwVTBGSHRuQSJ9.pZPVAnS4qZo6pJcecF2W9JArVCgHkdm4kLZd3J_sc0o.jd_YN5zKtg4rYbp0.SZ-7gaODzFKtGbF5GTKPW2009gkSMTmUi5iEL5d3duYgIh5KmQ47JWaZoUfut7hOkRntMHP93P11EjX0FEKW8XpmN5613gPlFnSMvkXWGwiTJN5TDSn2EDVfdu5aYXZHVmH3gaOaGNhXb3sJOOZg.wOW1V_IlGpL7xKZlCRaH5Q' \
--header 'signature: sig1=:T9QdWTGxAoQDeBB4rEQw0AiV8BuNraOLygoDdmMNrieZTtZ5lFmDTV78hd6hpWy46OCb4GIj0/5zGOmnEcSzBg==:' \
--data-raw '{"hello": "world"}'
```

yields `HTTP/1.1 200 OK`

while

```bash
# check the docker validiates
curl --location -i --request POST 'http://localhost:8080/verifysignature' \
--header 'Content-Type: application/json' \
--header 'Content-Digest: sha-256=:X48E9qOokqqrvdts8nOJRJN3OWDUoyWxBf7kbu9DBPE=:' \
--header 'Signature-Input: sig1=("content-digest" "x-ebay-signature-key" "@method" "@path" "@authority");created=1668613695' \
--header 'x-ebay-signature-key: eyJhbGciOiJBMjU2R0NNS1ciLCJlbmMiOiJBMjU2R0NNIiwiemlwIjoiREVGIiwiaXYiOiJwalh1LWlhY1NmRHNwc2lDIiwidGFnIjoiT090V2toaVV2NV9NZ2YwVTBGSHRuQSJ9.pZPVAnS4qZo6pJcecF2W9JArVCgHkdm4kLZd3J_sc0o.jd_YN5zKtg4rYbp0.SZ-7gaODzFKtGbF5GTKPW2009gkSMTmUi5iEL5d3duYgIh5KmQ47JWaZoUfut7hOkRntMHP93P11EjX0FEKW8XpmN5613gPlFnSMvkXWGwiTJN5TDSn2EDVfdu5aYXZHVmH3gaOaGNhXb3sJOOZg.wOW1V_IlGpL7xKZlCRaH5Q' \
--header 'signature: sig1=:T9QdWTGxAoQDeBB4rEQw0AiV8BuNraOLygoDdmMNrieZTtZ5lFmDTV78hd6hpWy46OCb4GIj0/5zGOmnEcSzBg==:' \
--data-raw '{"hello": "world"}'
```

yields: `HTTP/1.1 403` and the content: `null algorithm name`

**Comment by alexdawn** [comment] 2022-11-18 15:51
I've found the same with the other SDK:

From testing each of the repos against each other I've found the following:

<h2 data-pm-slice="1 1 []"></h2>

Sign \ Verify | NodeJS | Java | Java Docker
-- | -- | -- | --
NodeJS | ✅ | ✅ | :negative_squared_cross_mark:  java.lang.NullPointerException: null algorithm name
Java | ✅ | ✅ | :negative_squared_cross_mark: java.lang.NullPointerException: null algorithm name

<p></p>

**Comment by uherberg** [comment] 2022-12-07 17:18
@alexdawn I will have a look.

**Comment by uherberg** [comment] 2022-12-07 21:30
@alexdawn I looked into this. I think the cause is an incorrect JWE. This looks like a JWE that we previously used. In the latest code, we included a "cipher" claim inside the encrypted JWE that specifies whether we use Ed25519 or RSA. The Docker container reads this cipher claim and expects it. I updated the README to show the correct JWE in all places. Can you try with the JWE from the current README?

**Comment by uherberg** [comment] 2022-12-08 07:06
Closing this for now. Please let me know if this addresses your concern; if not, I can reopen.

**Comment by alexdawn** [comment] 2023-01-09 15:33
@uherberg sorry for the delay in response. The other ebay SDKs are generating their own JWEs from the same keys. 

I've hardcoded in the JWE from the readme into my project and the two SDKs and I'm now getting invalid signature responses from the docker instead of the null algorithm error (though the two SDKs and my own implementations are validating each other)

**Comment by uherberg** [comment] 2023-01-09 17:03
@alexdawn Which version (sha hash) of the docker container do you use? Can you please provide the exact payload / headers and JWE/private key that you use?

**Comment by LokeshRishi** [comment] 2023-01-10 21:33
@alexdawn I am getting 200 OK with the sample provided [here](https://github.com/eBay/digital-signature-verification-ebay-api#testing-a-signature).

Request:
```
curl --location --request POST 'http://localhost:8080/verifysignature' \
--header 'Content-Type: application/json' \
--header 'Signature-Input: sig1=("content-digest" "x-ebay-signature-key" "@method" "@path" "@authority");created=1658440308' \
--header 'Content-Digest: sha-256=:X48E9qOokqqrvdts8nOJRJN3OWDUoyWxBf7kbu9DBPE=:' \
--header 'Signature: sig1=:ZMUpAejnqrt6POSx02ltx3cT9YODV2r+Cem/BKOagDSfztKOtCsjP/MxZqmY+FVJ3/8E4BL76T9Fjty8oJnsAw==:' \
--header 'x-ebay-signature-key: eyJ6aXAiOiJERUYiLCJlbmMiOiJBMjU2R0NNIiwidGFnIjoiSXh2dVRMb0FLS0hlS0Zoa3BxQ05CUSIsImFsZyI6IkEyNTZHQ01LVyIsIml2IjoiaFd3YjNoczk2QzEyOTNucCJ9.2o02pR9SoTF4g_5qRXZm6tF4H52TarilIAKxoVUqjd8.3qaF0KJN-rFHHm_P.AMUAe9PPduew09mANIZ-O_68CCuv6EIx096rm9WyLZnYz5N1WFDQ3jP0RBkbaOtQZHImMSPXIHVaB96RWshLuJsUgCKmTAwkPVCZv3zhLxZVxMXtPUuJ-ppVmPIv0NzznWCOU5Kvb9Xux7ZtnlvLXgwOFEix-BaWNomUAazbsrUCbrp514GIea3butbyxXLNi6R9TJUNh8V2uan-optT1MMyS7eMQnVGL5rYBULk.9K5ucUqAu0DqkkhgubsHHw' \
--data-raw '{"hello": "world"}'
```

I can help debug the issue you are facing once you share the request details.

**Comment by uherberg** [comment] 2023-05-11 10:54
Closing as no more response received. Feel free to reopen if this is still an issue

**Closed as completed by uherberg** 2023-05-11 10:54 UTC
