### ISSUE TITLE
{"errors":[{"errorId":34916,"domain":"API_FULFILLMENT","category":"BUSINESS","message":"A post-transaction case exists on this order, seller refund can’t be triggered."}]}

### ISSUE THREAD

**Issue by mehboobafridi** [eBay/digital-signature-verification-ebay-api#24] opened 2023-05-27 06:17 UTC
Hello everyone,

I am using sell.fulfillment api to refund my cases. I have implemented the Digital Signature which is necessary for this call. The signature is tested on another endpoints like finance and was working successfully. However, when call the `https://api.ebay.com/sell/fulfillment/v1/order/{order_id}/issue_refund` API, it results with the captioned error.

**{"errors":[{"errorId":34916,"domain":"API_FULFILLMENT","category":"BUSINESS","message":"A post-transaction case exists on this order, seller refund can’t be triggered."}]}**

Here is my code highlights:

1. I am coding in PHP/Laravel.
2. I am using OAuth Token.
3. Here is my "refunder.config.json" contents.  `{
    "digestAlgorithm": "sha-256",
    "algorithm": "ED25519",
    "privateKeyStr": "-----BEGIN PRIVATE KEY-----\nMC4CA MY PRIVATE KEY gUE/\n-----END PRIVATE KEY-----",
    "jwe": "My JWE Key",
    "signatureParams": [
      "content-digest",
      "x-ebay-signature-key",
      "@method",
      "@path",
      "@authority"
    ]
  }`

4. Here is the code.
` $signature = new Signature(public_path("refunder-config.json"));

                $endpoint = 'https://api.ebay.com/sell/fulfillment/v1/order/' . $order_detail->OrderArray->Order->OrderID->__toString() . '/issue_refund';
                
                $USER_TOKEN = $config['production']['oauthUserToken'];
                
                $headers = [
                    'Authorization' => 'TOKEN ' .$USER_TOKEN,
                    'Accept' => 'application/json',
                    'Content-Type' => 'application/json'
                ];

                $caseType = $case_detail->caseType=='RETURN' ? 'BUYER_RETURN' : $case_detail->caseType;
                $body = '{
                    "orderLevelRefundAmount": {
                        "value":"' . $case_detail->claimAmount->value . '",
                        "currency":"' . $case_detail->claimAmount->currency . '"
                    },
                    "reasonForRefund":"' . $caseType . '",
                    "comment": "Refunded"
                }';

        
                $headers = $signature->generateSignatureHeaders($headers, $endpoint, "POST", $body);

                //Making a call
                $ch = curl_init($endpoint);
                if (!empty($body)) {
                    curl_setopt($ch, CURLOPT_POSTFIELDS, $body);
                }
                curl_setopt($ch, CURLOPT_HTTPHEADER, $this->curlifyHeaders($headers));
                curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                $response = curl_exec($ch);
                  curl_close($ch);`

Your help will be highly appreciated.

**Comment by uherberg** [comment] 2023-05-27 06:21
Hi @mehboobafridi. This error message doesn’t originate from the digital signature verification, i.e. your signature is correct. The error comes directly from the business logic of this API. Can you please file a ticket with the developer support team? I will close this issue here as it is unrelated to digital signatures

**Comment by mehboobafridi** [comment] 2023-05-27 06:22
Someone told me that there might be some bank charge back request by the buyer, but that is also not the case. We investigated that too. Also I am receiving this error on every open case.

I have tried many ebay forums but all in vain, no response, no help, it might be irrelevant here but thought you may help me.
Thanks

**Closed as completed by uherberg** 2023-05-27 06:21 UTC

**Comment by uherberg** [comment] 2023-05-27 06:24
@LokeshRishi Can you check with refund team what the issue is here?
@mehboobafridi Have you tried creating a ticket with the developer support? I am unfortunately not familiar with the details of the refund API.

**Comment by mehboobafridi** [comment] 2023-05-27 10:07
@uherberg No I haven't created yet. I think we need to pay for initiating any ticket with support team. isn't it?

**Comment by uherberg** [comment] 2023-05-27 18:21
@mehboobafridi Ah, apologies, I didn’t realize it’s paid.

**Comment by LokeshRishi** [comment] 2023-05-31 21:19
@mehboobafridi The API does not allow triggering a refund for orders with open cases. If a post-transaction case exists, sellers are prohibited from issuing a refund for the order until the case is resolved.
